### ISSUE TITLE
关于外接显示器

### ISSUE THREAD

**Issue by luhua98989898** [rote66/Hackintosh_HP_ZBOOK15VG5#1]
这个机器是没有办法外接HDMI显示器吗？ 没有任何一个方法实现吗？ 还有就是您的EFI里面就只有COLVER ，我复制了一个BOOT文件进去，可是引导界面没有安装盘符，是BOOT文件版本不对吗还是

**Comment by rote66** [comment]
hdmi口直通Quadro P600，可以尝试typec转vga，但是不保证能用。安装问题碰的都不一样，我只能说这个能开能用，但是装时遇到的问题我无法给出解决方案。你也可以考虑用（例如小兵的镜像）原本安装自带的efi去安装然后再换这个efi

**Comment by 19317362** [comment]
多谢楼主的这个。同款笔记本，直接替换SN以后就OK。
外接显示器，我从JD上买了一个JUA365，USB转双HDMI的，可以支持4K，反应有点慢。
之前在OSX 11.x + CLOVER时，是OK的。官方提供的有驱动。
由于XCODE+IOS开发需要，要升级到OSX 12.X，现在死活驱动不了USB-HDMI了。暂时放弃不折腾，就一个屏用

以上信息仅供参考。看再等一等，JUA365官方会不会出新驱动，看是否可以支持12.2

**Comment by stopyan** [comment]
> hdmi口直通Quadro P600，可以尝试typec转vga，但是不保证能用。安装问题碰的都不一样，我只能说这个能开能用，但是装时遇到的问题我无法给出解决方案。你也可以考虑用（例如小兵的镜像）原本安装自带的efi去安装然后再换这个efi

Type-c经测试也是由P600直连的外输画面...也就楼上USB displaylink方案能在老maoc os里面用一用。

**Comment by rote66** [comment]
> > hdmi口直通Quadro P600，可以尝试typec转vga，但是不保证能用。安装问题碰的都不一样，我只能说这个能开能用，但是装时遇到的问题我无法给出解决方案。你也可以考虑用（例如小兵的镜像）原本安装自带的efi去安装然后再换这个efi
> 
> Type-c经测试也是由P600直连的外输画面...也就楼上USB displaylink方案能在老maoc os里面用一用。

是的，C口也是走独显，在我另一台光5上也是一样。除了有线ipad随航外要不就是在macos12上通过OCLP修补nvidia webdriver来驱动p600，不过能否驱动没有试过
